branches:
  only:
  - master

os: linux

dist: focal

language: minimal

git:
  quiet: true

cache:
  directories:
    - /home/travis/cache

env:
  global:
    - LANG=en_US.UTF-8
    - REPO_MAKE_CACHE=$HOME/cache
    - REPO_MAKE_TARGET=$HOME/repo
    - REPO_MAKE_PKGBUILDS=$TRAVIS_BUILD_DIR

jobs:
  - env: REPO_MAKE_ARCH=x86_64 REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg.conf
    arch: amd64
  - env: REPO_MAKE_ARCH=armv6h REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg-armv6h.conf
    arch: arm64
  - env: REPO_MAKE_ARCH=armv7h REPO_MAKE_MAKEPKG_CONF=./.ci/makepkg-armv7h.conf
    arch: arm64

before_script:
  - ./.ci/setup_arm_build.sh
  - sudo locale-gen en_US.UTF-8
  - sudo update-locale LANG=en_US.UTF-8
  - git clone https://github.com/VDR4Arch/$REPO_MAKE_ARCH.git --branch master --single-branch $HOME/repo || true
  - rm -rf $HOME/repo/.git

script:
  - sudo ./.ci/repo-make-ci.sh

before_deploy:
  - sudo chown -R $USER:$USER $HOME/repo
  - ./.ci/genindex.sh $HOME/repo $REPONAME

#deploy:
#  provider: pages
#  token: $GITHUB_TOKEN
#  skip_cleanup: true
#  local_dir: $HOME/repo/
#  repo: VDR4Arch/$REPO_MAKE_ARCH
#  target_branch: master
#  on:
#    repo: $TRAVIS_REPO_SLUG
#    branch: master
