name: Bug report
description: Report a compile error, configuration problem or packaging issue.
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To reproduce
      description: Provide the specific set of steps we can follow to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What would you expect to happen after following those instructions?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any additional information here.
    validations:
      required: false
  - type: checkboxes
    id: checklist
    attributes:
      label: Issue checklist
      description: Please double-check that you have done each of the following things before submitting the issue.
      options:
        - label: I searched for previous reports in [the issue tracker](https://github.com/VDR4Arch/vdr4arch/issues)
          required: true
        - label: My report contains all necessary details
          required: true
