post_install() {
  if [ ! -f var/lib/vdradmin/vdradmind.conf ]; then
    yes | vdradmind --config > /dev/null
  fi

  mkdir -p var/lib/vdradmin
  chown -R vdr:vdr var/lib/vdradmin

  mkdir -p var/cache/vdradmin
  chown -R vdr:vdr var/cache/vdradmin

  mkdir -p var/log/vdradmin
  chown -R vdr:vdr var/log/vdradmin
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -r var/lib/vdradmin 2> /dev/null
  rm -r var/cache/vdradmin 2> /dev/null
  rm -r var/log/vdradmin 2> /dev/null
}
