#!/usr/bin/bash
FILE=/etc/systemd/system/vdr.service.d/wait-for-devices.conf

install -D /dev/null $FILE
cd /dev
for dev in dvb/adapter*/*; do
  stringpart=$(tr / - <<< $dev)
  echo Wants=dev-$stringpart.device >> $FILE
  echo After=dev-$stringpart.device >> $FILE
done
