#!/usr/bin/bash
FILE=/etc/systemd/system/vdr.service.d/wait-for-devices.conf

if [ -d /dev/dvb/adapter0 ]; then
  mkdir -p $(dirname $FILE)
  echo '[Unit]' > $FILE

  cd /dev
  for dev in dvb/adapter*/*; do
    stringpart=$(tr / - <<< $dev)
    echo "Wants=dev-$stringpart.device" >> $FILE
    echo "After=dev-$stringpart.device" >> $FILE
  done
  systemctl daemon-reload
else
  rm -f $FILE
fi